### PR TITLE
Fix spelling of LaunchDarkly

### PR DESCRIPTION
**Pull request by mlafeldt**

### CODE REVIEW

**Comment by mlafeldt** [comment]
I noticed that you changed the default branch from v2 to v3. However, my changes in v2 haven't been merged to v3 yet. On purpose?

**Comment by eli-darkly** [comment]
@mlafeldt 
> my changes in v2 haven't been merged to v3 yet. On purpose?

No, we just hadn't got around to it. Will merge now and add a v3 release tag soon.

Thanks for the copyediting!

**Comment by eli-darkly** [comment]
FYI, these merges sometimes get delayed because we also maintain a private repo with other ongoing changes and it has to be kept in sync.

**Comment by mlafeldt** [comment]
OK! No worries.

**Pull request merged**
