### PR TITLE
Implement status to stop connecting to stream after Close() is called

### PR DESCRIPTION
**Pull request by kaironess**

### CODE REVIEW

**Comment by ashanbrown** [comment]
Thanks for your PR @kaironess.  We'd love to know a bit more about your need for this fix, if you'd be willing to share more information.  The third-party EventSource Stream struct that we use does not have a close method, which would be our preferred method of stopping processing the stream.  I believe your changes are designed to stop the goroutines that are processing the stream (and potentially writing the data into redis if you're using redis for the feature store).  We'd be open to this sort of change, although our preference would be to tear down the handlers immediately rather than waiting for an event or error to be processed.  I think that we could use select across multiple channels in each goroutine and close a "stop" channel that is received by both the event and error processors (see https://tour.golang.org/concurrency/5).  Please let us know what you think about that approach.

**Comment by kaironess** [comment]
The main desire / goal is to stop the log messages and attempts to connect after an error or after timeout. I understand that its preferable to just call the close method of EventSource's Stream (when it gets implemented), but until then I think it's necessary to have some kind of fix in the meantime. The fact that processes related to the client continue despite the close method being called seems unintuitive and like cleanup isn't complete.

I don't have any qualms on how the goal is accomplished, so long as it's possible.

**Comment by ashanbrown** [comment]
Thanks @kaironess .  I have a private PR I'm testing out and if testing goes smoothly, I'll should have public PR visible for you to look at by the end of the week.  It looks like a `Close()` method was added to the upstream copy of eventsource at https://github.com/donovanhide/eventsource, but it looks like there are still some issues remaining with that, so I'm going to skip that part and implement an `Close()` that stops listening to the eventsource using channels as the synchronization mechanism.

**Comment by ashanbrown** [comment]
@kaironess Please try out 2.1.0.  It should stop processing after `Close()` is called.

**Comment by ashanbrown** [comment]
Should be fixed by https://github.com/launchdarkly/go-client/commit/d08f76dec42aaab2496bedb7c94ce77d6a2f87c2

**Pull request closed without merging**
